# Generated by Django 3.2 on 2022-08-24 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_curso_miembro'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='categoria_id',
            field=models.ForeignKey(db_column='categoria_id', default=2, on_delete=django.db.models.deletion.RESTRICT, related_name='Cursos', to='api.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='autor_id',
            field=models.ForeignKey(db_column='autor_id', on_delete=django.db.models.deletion.RESTRICT, to='api.miembro', verbose_name='Autor'),
        ),
    ]
